### ISSUE TITLE
build.gradle reference SDK project and the SDK project is not in this repository

### ISSUE THREAD

**Issue by JohnMAustin78** [skypeonramps/SkypeAndroidMobileSDK#1]
compile project(':MobileSdk')  

This line does not work because the MobileSdk project is not included in the repo.  The sample does not build.

**Comment by skypeonramps** [comment]
Hello John, can you try it now. Have uploaded an updated sample app.
If it still doesn't work for you, please feel free to re-open with the error in the comment.

Thanks for reporting this.
